### ISSUE TITLE
使用自定义RequestCallback有问题

### ISSUE THREAD

**Issue by Vence0815** [ZYRzyr/ApiClient#1]
在使用自定义RequestCallback的时候提示subscribe没有这个类型的方法，可以看截图。你的demo里面也有这个问题。然后我把Observer<ResponseWrapper<"T">>   改成Observer<"T"> (不要在意引号，不加打不出来字)就不会报错，这是什么问题？不用这个泛型怎么判断自己的数据的code值呢，求大神指导下，看了很久没看出来问题。。。

<img width="935" alt="2018-01-26 11 38 33" src="https://user-images.githubusercontent.com/16802661/35447548-f5b548a0-02f2-11e8-8e7c-0d145e1636e7.png">

**Comment by ZYRzyr** [comment]
@Vence0815 
抱歉才看见。
是我的疏忽，没有写全，已经补充了
[请看这里](https://github.com/ZYRzyr/ApiClient/commit/7297244d40ac847aca50bb4c750e19dcfead7e77)
原因就是，`GitHubService`中`API`方法的返回值要改一改
