### ISSUE TITLE
您好 我按照这种写法 RxJava的Subscribe一直需要我创建一个类。。。上网查了半天没能解决

### ISSUE THREAD

**Issue by ChristingLi** [ZYRzyr/ApiClient#2]
![default](https://user-images.githubusercontent.com/32630546/38465632-ab77d6cc-3b50-11e8-8682-79803cdac535.png)

**Comment by ZYRzyr** [comment]
@ChristingLi 
[这个里面的回答](https://github.com/ZYRzyr/ApiClient/issues/1)能解决您的问题吗？
