### ISSUE TITLE
NetworkScheduler中加入生命周期绑定可以吗？

### ISSUE THREAD

**Issue by sth0409** [ZYRzyr/ApiClient#3]
https://i.imgur.com/CjMtKN5.png
像这样在NetworkScheduler中加入绑定生命周期是不是更简洁？

**Comment by sth0409** [comment]
![sheqz 9 znnb6e2yvie8sk](https://user-images.githubusercontent.com/19368488/52930604-05f2ab00-3384-11e9-9c67-638f225e5a6d.png)

**Comment by ZYRzyr** [comment]
你说的对
